version: "3"
services:
  backend:
    depends_on:
      - store
    restart: always
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  store:
    image: mysql:8.0
    container_name: api_mysql_db
    env_file: .env
    volumes:
      - mysqldata:/data/mysql

volumes:
  mysqldata: