version: "3"
services:
  api:
    depends_on:
      - store
    restart: always
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  store:
    image: mongo:4.4
    container_name: mongo_db_api
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: